### ISSUE TITLE
[babel] /victory/lib/index.js: Unknown option /victory/.babelrc.stage

### ISSUE THREAD

**Issue by alx** [FormidableLabs/victory#199]
Hi FormidableLabs,

I've an issue while using victory, and I'm not fluent enough with webpack/babel to know how to debug it, could you help me?

It seems to be related with #78 

At first look, there's a strange path at the beginning of the error log: `ERROR in ./~/victory/lib/index.js`

Thanks!

```
alx@debian:~/code/htdocs$ npm start

> react-webpack-template@0.0.0 start /home/alx/code/htdocs
> webpack --progress --colors --watch
                                                                                64% 151/166 build modules[BABEL] Note: The code generator has deoptimised the styling of "/home/alx/code/htdocs/node_modules/momentHash: a082708dea569976f2ed                    
Version: webpack 1.12.10
Time: 25587ms
                    Asset     Size  Chunks             Chunk Names
    ./assets/js/bundle.js  1.29 MB       0  [emitted]  main
./assets/js/bundle.js.map  2.06 MB       0  [emitted]  main
    + 329 hidden modules

ERROR in ./~/victory/lib/index.js
Module build failed: ReferenceError: [BABEL] /home/alx/code/htdocs/node_modules/victory/lib/index.js: Unknown option: /home/alx/code/htdocs/node_modules/victory/.babelrc.stage
    at Logger.error (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/alx/code/htdocs/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/home/alx/code/htdocs/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/home/alx/code/htdocs/node_modules/babel-loader/index.js:88:12)
 @ ./assets/js/components/Network.react.js 3:15-33
```

package.json

```
{
  "name": "dataviz",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack --progress --colors --watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "BSD-2-Clause",
  "dependencies": {
    "classnames": "^2.2.3",
    "flux": "^2.1.1",
    "keymirror": "^0.1.1",
    "react": "^0.14.5",
    "react-bootstrap-datetimepicker": "^0.0.22",
    "react-dom": "^0.14.5",
    "react-search-input": "^0.6.0",
    "react-text-filter": "^2.0.1",
    "victory": "^0.4.0"
  },
  "devDependencies": {
    "babel-core": "^6.3.26",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "webpack-dev-server": "^1.12.9"
  }
}
```

webpack.config.js

```
module.exports = {
  cache: true,
  entry: './assets/js/app',
  output: {
    filename: './assets/js/bundle.js'
  },
  devtool: 'source-map',
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react']
        }
      },
    ]
  }
};
```

header of ./assets/js/components/Network.react.js 

```
var React = require('react');
var ReactDOM = require('react-dom');
var AlertActions = require('../actions/AlertActions');

import * as V from "victory"
```

**Comment by boygirl** [comment]
hi @alx, unfortunately Victory has not yet upgraded to Babel 6. If you revert to Babel 5 the error should go away.

**Comment by exogen** [comment]
Using the same Babel version isn't required, I think the issue is that `babel-loader` needs to be told to ignore stuff in `node_modules`, otherwise it will try to transpile all dependencies as well (but we already distribute the transpiled code in `lib`).

It should work if you update the loader like so:

```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ['es2015', 'react']
        }
      },
```

**Comment by alx** [comment]
Thanks @exogen, it solved this issue and the compile time is greatly improved.
