### ISSUE TITLE
V36.2.0 victory-native compile error

### ISSUE THREAD

**Issue by SaeedZhiany** [FormidableLabs/victory#2020]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I just upgraded victory-native from `v35.5.5` to `v36.2.0` and when I run the application I got this error stack.

```bash
error: Error: Unable to resolve module ./path-helpers from C:\Users\SAEED\workspace\App\node_modules\victory-core\lib\victory-primitives\point.js:

None of these files exist:
  * node_modules\victory-core\lib\victory-primitives\path-helpers(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\victory-core\lib\victory-primitives\path-helpers\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | "use strict";
  2 |
  3 | Object.defineProperty(exports, "__esModule", {
  4 |   value: true
    at ModuleResolver.resolveDependency (C:\Users\SAEED\workspace\App\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (C:\Users\SAEED\workspace\App\node_modules\metro\src\node-haste\DependencyGraph.js:353:43)
    at Object.resolve (C:\Users\SAEED\workspace\App\node_modules\metro\src\lib\transformHelpers.js:271:42)
    at resolve (C:\Users\SAEED\workspace\App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:571:33)
    at C:\Users\SAEED\workspace\App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\SAEED\workspace\App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:586:33)
    at C:\Users\SAEED\workspace\App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\SAEED\workspace\App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

```

**Comment by SaeedZhiany** [comment]
running `react-native start --reset-cache` will solve the problem.
