### ISSUE TITLE
Tests: Element type is invalid

### ISSUE THREAD

**Issue by tqn-treezor** [FormidableLabs/victory#2175]
# Questions

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When trying to implement tests on React Native Victory Charts, I took a minimal example from the Native doc: https://formidable.com/open-source/victory/docs/native

I also combined the jest configuration with mine:
```js
module.exports = {
  preset: 'react-native',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testPathIgnorePatterns: ['dist', 'coverage'],
  moduleDirectories: ['<rootDir>/node_modules', 'node_modules'],
  moduleNameMapper: {
    '^@treezor/caas(.*)$': '<rootDir>/$1',
    '\\.svg': '<rootDir>/__mocks__/svgMock.js',
  },
  setupFiles: [
    './jest.setup.js',
    './node_modules/react-native-gesture-handler/jestSetup.js',
  ],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|@react-native|react-native-iphone-x-helper|@react-navigation|native-base|date-fns|react-native-svg|victory)',
  ],
  transform: {
    '^.+\\.jsx?$': 'babel-jest',
  },
  moduleNameMapper: {
    '^@treezor/mobile-ui-kit/(.*)': '<rootDir>/$1',
    '\\.svg': '<rootDir>/__mocks__/svgMock.js',
  },
};

```

But when trying to launch `npm run test`, I got an `Element type is invalid` error.

The entire error trace is the following one:
```
● renders correctly

    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `VictoryContainer`.

      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16180:21)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16208:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5358:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5418:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7984:28)
      at updateHostComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8568:3)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9997:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    
    Check the render method of `VictoryContainer`.
        at _default (myFolder/packages/ui-kit/node_modules/victory-native/src/components/victory-container.js:20:22)
        at VictoryChart (myFolder/packages/ui-kit/node_modules/victory-chart/es/victory-chart.js:26:37)
        at WrappedComponent
        at View
        at Component (myFolder/packages/ui-kit/node_modules/react-native/jest/mockComponent.js:28:18)
        at TestChart (myFolder/packages/ui-kit/src/components/balance/TestChart.tsx:151:34)

      at printWarning (node_modules/react/cjs/react.development.js:220:30)
      at error (node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2215:7)
      at _default.renderContainer (node_modules/victory-native/src/components/victory-container.js:136:9)
      at _default.render (node_modules/victory-core/es/victory-container/victory-container.js:215:19)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8459:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8409:24)

  console.error
    The above error occurred in the <View> component:
    
        at View
        at Component (myFolder/packages/ui-kit/node_modules/react-native/jest/mockComponent.js:28:18)
        at _default (myFolder/packages/ui-kit/node_modules/victory-native/src/components/victory-container.js:20:22)
        at VictoryChart (myFolder/packages/ui-kit/node_modules/victory-chart/es/victory-chart.js:26:37)
        at WrappedComponent
        at View
        at Component (myFolder/packages/ui-kit/node_modules/react-native/jest/mockComponent.js:28:18)
        at TestChart (myFolder/packages/ui-kit/src/components/balance/TestChart.tsx:151:34)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
```

May it be related to that issue? https://github.com/kristerkari/react-native-svg-transformer/issues/131

### Reproduction

Pretty hard to reproduce since it is a mobile error.

**Comment by rrascon-gainnoval** [comment]
Did you find any solution for this?
