### ISSUE TITLE
VictoryLegend cannot be used as a JSX component

### ISSUE THREAD

**Issue by Nosherwan** [FormidableLabs/victory#2513]
**Describe the bug**

I recently changed from intel MacBook Pro to m2 MacBookair, this however should not create the issue.
The code is unchanged that I am compiling.
At first the linter shows the below error:

```
(alias) class VictoryLegend
import VictoryLegend
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
'VictoryLegend' cannot be used as a JSX component.
  Its instance type 'VictoryLegend' is not a valid JSX element.
    Type 'VictoryLegend' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.ts(2786)
```
The build fails for my next.js project with the following type error:

```
Type error: 'VictoryLegend' cannot be used as a JSX component.
#11 24.43   Its instance type 'VictoryLegend' is not a valid JSX element.
#11 24.43     The types returned by 'render()' are incompatible between these types.
#11 24.43       Type 'React.ReactNode' is not assignable to type 'import("/app/node_modules/@types/hoist-non-react-statics/node_modules/@types/react/index").ReactNode'.
#11 24.43 
#11 24.43   16 |                        scale={{ x: 'time' }}
#11 24.43   17 |                >
#11 24.43 > 18 |                        <VictoryLegend
#11 24.43      |                         ^
#11 24.43   19 |                                x={300}
#11 24.43   20 |                                y={50}
#11 24.43   21 |                                title='Legend'
#11 24.54 
#11 24.54 > Build error occurred
#11 24.54 Error: Call retries were exceeded
#11 24.54     at ChildProcessWorker.initialize (/app/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
#11 24.54     at ChildProcessWorker._onExit (/app/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
#11 24.54     at ChildProcess.emit (events.js:400:28)
#11 24.54     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12) {
#11 24.54   type: 'WorkerError'
#11 24.54 }
```

**Victory version**
36.6.0

React versions:
    "next": "12.2.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey

**Additional context**

**Comment by Nosherwan** [comment]
Ok for now upgrading react types has resolved the issue.
It is a bit odd that I have to use react 18 typings with react 17.
"react": "17.0.2",
"react-dom": "17.0.2",
"@types/react": "18.0.25",

**Comment by scottrippey** [comment]
It might have been 2 different versions of `@types/react` that were incompatible.

**Comment by woozyking** [comment]
One good way of resolving this is through `npm`'s `overrides`, or `yarn`'s equivalent `resolutions` configs:

```json
...
  "resolutions": {
    "@types/react": "^18.2.17"
  },
  "overrides": {
    "@types/react": "^18.2.17"
  },
...
```
