### ISSUE TITLE
TypeError: Cannot read property 'uid' of undefined 

### ISSUE THREAD

**Issue by jennylia** [FormidableLabs/victory#375]
Running an npm test in https://github.com/FormidableLabs/victory-chart would give me this error.
Would this be something simple to fix?
Logs:
[builder:proc:start] Command: karma start node_modules/builder-victory-component/config/karma/karma.conf.js
26 09 2016 15:03:31.928:ERROR [karma]: TypeError: Cannot read property 'uid' of undefined
    at /Users/jennylian/play/victory-chart/victory-chart/node_modules/graceful-fs/polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:123:15)

Thanks,
Jen

**Comment by jennylia** [comment]
npm install graceful-fs@4.1.8 fixed this issue for me.
Please view:
https://github.com/isaacs/node-graceful-fs/issues/88
