### ISSUE TITLE
Failure when running `npm start`

### ISSUE THREAD

**Issue by GreenGremlin** [FormidableLabs/victory#536]
I'm hoping to try out the demo, which appears to be accessible from the webpack-dev-server. I'm new to victory and builder, so I'm not sure if I'm missing something here. I'm on the master branch of the victory repo, I've run `npm install`, and now I'm trying to run `npm start` and it's failing.

Here is the failure message from `npm start` (I've tried to filter to just the relevant lines):

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.loaders[0].loader should be one of these:
   non-empty string | non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]
   Details:
    * configuration.module.loaders[0].loader should be a string.
    * configuration.module.loaders[0].loader should be a string.
    * configuration.module.loaders[0].loader should be an instance of function.
    * configuration.module.loaders[0].loader should be an object.
    * configuration.module.loaders[0].loader should be one of these:
      non-empty string | function | object { loader?, options?, query? }
    * configuration.module.loaders[0].loader should be an instance of function.
    * configuration.module.loaders[0].loader should be an array:
      [non-empty string | function | object { loader?, options?, query? }]
    * configuration.module.loaders[0].loader should be one of these:
      non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/jonathan/code/github/victory/node_modules/builder-victory-component-dev/node_modules/webpack-dev-server/node_modules/webpack/lib/webpack.js:19:9)
    at processOptions (/Users/jonathan/code/github/victory/node_modules/builder-victory-component-dev/node_modules/webpack-dev-server/bin/webpack-dev-server.js:209:13)
    at Object.<anonymous> (/Users/jonathan/code/github/victory/node_modules/builder-victory-component-dev/node_modules/webpack-dev-server/bin/webpack-dev-server.js:228:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
[builder:proc:error] Code: 1, Command: webpack-dev-server --config node_modules/builder-victory-component/config/webpack/demo/webpack.config.hot.js --colors --inline --hot --content-base demo
[builder:builder-core:end:24146] Task: concurrent server-hot, server-test, Error: Command failed: sh -c webpack-dev-server --config node_modules/builder-victory-component/config/webpack/demo/webpack.config.hot.js --colors --inline --hot --content-base demo
```

**Comment by GreenGremlin** [comment]
I was on Node 4, I tried again on Node 6 and it worked. I wonder, is this likely a builder issue or an issue with builder-victory-component-dev?

**Comment by ryan-roemer** [comment]
For Node 4, what is the output of:

```sh
$ which webpack
```

?

**Comment by ryan-roemer** [comment]
Actually I've repro'ed it. Problem is:

```
 cat node_modules/builder-victory-component-dev/node_modules/webpack-dev-server/package.json | grep '"webpack"'
    "webpack": ">=1.3.0 <3"
    "webpack": "^1.13.2"
```

The restriction is `<3` and we need `1` to match the prod archetype. Will open a fix soon.

**Comment by GreenGremlin** [comment]
Cool, thanks!
