### ISSUE TITLE
victory-pie "npm run storybook" error

### ISSUE THREAD

**Issue by dishui** [FormidableLabs/victory#595]
ERROR in ./.storybook/config.js
Module build failed: Error: [BABEL] formidablelabs/victory-pie/.storybook/config.js: Couldn't resolve extends clause of formidablelabs/victory-pie/builder-victory-component/config/babel/.babelrc in base
    at Logger.error (formidablelabs/victory-pie/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at ConfigChainBuilder.mergeConfig (formidablelabs/victory-pie/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:186:32)
    at buildConfigChain (formidablelabs/victory-pie/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:64:11)
    at OptionManager.init (formidablelabs/victory-pie/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at File.initOptions (formidablelabs/victory-pie/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (formidablelabs/victory-pie/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (formidablelabs/victory-pie/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (formidablelabs/victory-pie/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (formidablelabs/victory-pie/node_modules/babel-loader/lib/index.js:163:20)
 @ multi preview

**Comment by boygirl** [comment]
fixed :)
