### ISSUE TITLE
npm installing Victory fails when Babel 6 .babelrc file is present 

### ISSUE THREAD

**Issue by dandelany** [FormidableLabs/victory#78]
I am trying to install Victory from `master` in an existing project which is using Babel 6 (and therefore contains a .babelrc file with `presets`). Running `npm install` yields this error from the postinstall step:

```
> victory@0.0.2 build-lib /Users/dand/Documents/repos/victory-playground/node_modules/victory
> npm run clean-lib && babel --stage 0 src -d lib


> victory@0.0.2 clean-lib /Users/dand/Documents/repos/victory-playground/node_modules/victory
> rimraf lib

ReferenceError: [BABEL] src/index.js: Unknown option: /Users/dand/Documents/repos/victory-playground/.babelrc.presets
    at Logger.error (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/dand/Documents/repos/victory-playground/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.exports.transform (/Users/dand/Documents/repos/victory-playground/node_modules/babel/lib/babel/util.js:40:22)
    at Object.exports.compile (/Users/dand/Documents/repos/victory-playground/node_modules/babel/lib/babel/util.js:49:20)
```

Looks like this is happening because Victory is using Babel 5.5, but when the postinstall step runs `babel`, it finds the Babel 6 .babelrc file in my project and tries to use that. Since 'presets' is not a valid .babelrc option in Babel 5.5, it fails. Thoughts on fixing:

- For anyone else running into this, a temporary workaround is rename your `.babelrc` file to something else, then `npm install`, then rename it back.
- In theory, there shouldn't be a problem with running 2 different versions of Babel like this - maybe there is an option to make `babel` ignore the .babelrc file if it's present.
- But eventually, Victory should probably just upgrade to use Babel 6. I can help with this if you'd like, shouldn't be too hard.

FWIW, here's the contents of my .babelrc:

```
{
    "presets": [ "react", "es2015" ]
}
```

**Comment by ryan-roemer** [comment]
Hi! Random smattering of possibly uninformed thoughts there:

@exogen is our resident expert in "WHY BABEL? WHY?" `.babelrc`-related issues.

@boygirl -- Remind me of our Radium dependencies (if any) for Victory (wrt decorators and other non-babel6-compatible things)? Can you link in any other babel6 tickets here?

**Comment by ryan-roemer** [comment]
... but we may be coming to the point of doing the "no postininall `lib`" thing (which would solve this issue) and telling git/non-NPM-users to suck it up.

**Comment by boygirl** [comment]
@ryan-roemer we're using radium decorators, and I also remember having to lower the babel stage to accommodate our `static PropTypes...` syntax.

`postinstall` has been a pain for as long as we've been using it. I would vote for building `lib` explicitly before the scripts that require it. Might make development flow a little slower... Thoughts?

**Comment by dandelany** [comment]
Thanks for the comments, all. Opened #79 with a fix I discovered, though an upgrade to Babel 6 should still be considered eventually. Maybe we should open a new ticket for that.

**Comment by dandelany** [comment]
(it's entirely possible that removing your `postinstall` altogether, as you are discussing, is a good idea too - but I'm abstaining from that vote since I haven't looked into the details of what it's doing :smile: )

**Comment by ryan-roemer** [comment]
@boygirl -- For

> Might make development flow a little slower... Thoughts?

Our discussion is on some ticket I can't find, but having a postinstall `lib` has the advantages of allowing `git` / non-NPM dependency easily for a forked code situation.

**Comment by boygirl** [comment]
@dandelany also to note, I'm about to update this whole component to use builder since I'm just finishing updating all the dependent repos.

**Comment by coopy** [comment]
@dandelany Has this been fixed / can this be closed?

**Comment by dandelany** [comment]
Oops - I still have to merge this into the new master branch (see related pull request). Will do it first thing tomorrow.

**Comment by neverfox** [comment]
I'm having what *might* be a related problem. When doing a full, fresh npm install that includes victory in my Babel 6 project, many of my dependencies don't make it into node_modules. If I remove victory, all is well.

**Comment by dandelany** [comment]
Interesting @neverfox - you could try checking out the dandelany/victory#fix-babelrc branch which fixes this specific issue (see #79 - ready to merge btw), but I suspect your problem is not quite the same, so you may want to open a new ticket. Also FWIW, you may want to just try running `npm install` again after the first attempt fails, if you haven't already - sometimes I have problems the first time, but running it again works (strangely),

**Comment by austinpray** [comment]
```

**Comment by dandelany** [comment]
Closing this issue since #79 was merged - @neverfox feel free to file another ticket if you're still having other issues.
