### ISSUE TITLE
Victory breaks Enzyme tests

### ISSUE THREAD

**Issue by alexthebake** [FormidableLabs/victory#923]
Hey,

For some reason I keep getting the following error whenever I try to test any of my components that contain a Victory component:
```
TypeError: Cannot set property 'pointerEvents' of undefined
      at Object.CSSPropertyOperations.setValueForStyles (node_modules/react-dom/lib/CSSPropertyOperations.js:195:26)
      at ReactDOMComponent.Mixin._updateDOMProperties (node_modules/react-dom/lib/ReactDOMComponent.js:888:29)
      at ReactDOMComponent.Mixin.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:518:12)
      at Object.ReactReconciler.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:234:44)
      at ReactDOMComponent.Mixin._createInitialChildren (node_modules/react-dom/lib/ReactDOMComponent.js:701:32)
      at ReactDOMComponent.Mixin.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:520:12)
      at Object.ReactReconciler.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at ReactCompositeComponent.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
      at ReactCompositeComponent.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at ReactCompositeComponent.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
      at ReactCompositeComponent.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at ReactCompositeComponent.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
      at ReactCompositeComponent.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at ReactCompositeComponent.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
      at ReactCompositeComponent.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at mountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:102:32)
      at ReactReconcileTransaction.TransactionImpl.perform (node_modules/react-dom/lib/Transaction.js:141:20)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:124:15)
      at ReactDefaultBatchingStrategyTransaction.TransactionImpl.perform (node_modules/react-dom/lib/Transaction.js:141:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:95:27)
      at Object.ReactMount._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:317:18)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:399:32)
      at Object.ReactMount.render (node_modules/react-dom/lib/ReactMount.js:420:23)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:89:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:200:24)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Context.<anonymous> (tests/components/views/dashboard/HomeDashboard-test.jsx:31:5)
```

**Relevant Packages**
- react: ^15.6.1
- react-dom: ^15.6.1
- victory: ^0.24.5
- enzyme: ^2.9.1
- jsdom: ^11.1.0
- mocha: ^3.4.2
- react-test-renderer: ^15.6.1

To make sure it was Victory and not anything else in my app causing this issue, I made the following test (which fails, returning the error posted above):
```jsx
import React from 'react';
import { mount } from 'enzyme';
import { VictoryChart } from 'victory';

describe('Victory works', () => {
  it('does not break', () => {
    mount(<VictoryChart />)
  });
});
```

I haven't been able to find any information about this, and I'm not exactly sure where the problem is coming from. I tried digging through the Victory source, but I haven't been able to find anything. Any help would be very much appreciated!

Thanks.

**Comment by alexthebake** [comment]
Well... I'm a little confused. Maybe someone knows more about why this is the case, but I tried upgrading various packages to see if that would solve the issue, and it turns out upgrading jsdom from v11.1.0 to v11.6.2 fixed my issue. I'll try to investigate some more and see what changed, but I find this especially odd since it seemed like the error was coming from ReactDOM. I'll close this issue for now.
